# Site settings
title: Cats&Dogs
description: > # this means to ignore newlines until "baseurl:"
    My progress in the course project.
baseurl: "/ift6266h16"
url: "https://http://rizar.github.io/ift6266h16/"
github_username:  rizar

# Build settings
markdown: kramdown
